/**
 * Boot Scene
 * Handles asset preloading before the main game starts
 */
import Phaser from 'phaser';
import { Services } from '../services';
import { ASSET_ENTRIES } from '../assets-manifest';

// Import singletons for service registration
import playerManager from '../managers/PlayerManager';
import projectileManager from '../managers/ProjectileManager';
import xpOrbManager from '../managers/XPOrbManager';
import enemyManager from '../managers/EnemyManager';
import combatSystem from '../systems/CombatSystem';
import spawnSystem from '../systems/SpawnSystem';
import playerStatsSystem from '../systems/PlayerStatsSystem';
import levelProgressionSystem from '../systems/LevelProgressionSystem';
import levelStatsTracker from '../systems/LevelStatsTracker';
import magnetismSystem from '../systems/MagnetismSystem';

export default class BootScene extends Phaser.Scene {
    constructor() {
        super({ key: 'BootScene' });
    }
    
    preload() {
        // Automatically load all PNG assets from the generated manifest
        // The manifest is auto-generated by running: node generate-assets-manifest.js
        for (const entry of ASSET_ENTRIES) {
            this.load.image(entry.key, `/Scalar.Game/${entry.path}`);
        }
        
        // Optional: Add loading progress bar
        this.createLoadingBar();
    }
    
    createLoadingBar() {
        const width = this.cameras.main.width;
        const height = this.cameras.main.height;
        
        // Create loading text
        const loadingText = this.add.text(width / 2, height / 2 - 50, 'Loading...', {
            fontSize: '32px',
            color: '#ffffff'
        });
        loadingText.setOrigin(0.5);
        
        // Create progress bar
        const progressBar = this.add.graphics();
        const progressBox = this.add.graphics();
        progressBox.fillStyle(0x222222, 0.8);
        progressBox.fillRect(width / 2 - 160, height / 2, 320, 50);
        
        // Update progress
        this.load.on('progress', (value: number) => {
            progressBar.clear();
            progressBar.fillStyle(0xffffff, 1);
            progressBar.fillRect(width / 2 - 150, height / 2 + 10, 300 * value, 30);
        });
        
        this.load.on('complete', () => {
            progressBar.destroy();
            progressBox.destroy();
            loadingText.destroy();
        });
    }
    
    create() {
        // Register all singleton services with the ServiceLocator
        this.initializeServices();
        
        // LEGACY COMPATIBILITY: Create 'enemy' as an alias for 'land/macro/rockgiant' texture
        // This avoids loading the same asset twice while maintaining backward compatibility.
        // 
        // Future enhancement: If more aliases are needed, consider moving this to a
        // configuration object like: const ASSET_ALIASES = { 'enemy': 'land/macro/rockgiant', ... }
        if (this.textures.exists('land/macro/rockgiant') && !this.textures.exists('enemy')) {
            const rockgiantTexture = this.textures.get('land/macro/rockgiant');
            const sourceImage = rockgiantTexture.getSourceImage() as HTMLImageElement;
            this.textures.addImage('enemy', sourceImage);
        }
        
        // Once loading is complete, start the menu scene
        this.scene.start('MenuScene');
    }

    /**
     * Initialize the ServiceLocator with all game services
     * This breaks circular dependencies by providing centralized access
     * 
     * Note: StaminaSystem and FuelSystem require config initialization
     * and are registered via PlayerStatsSystem.initializeDifficulty()
     * CompanionManager is scene-specific and registered per-scene
     */
    private initializeServices(): void {
        // Managers
        Services.register('playerManager', playerManager);
        Services.register('projectileManager', projectileManager);
        Services.register('xpOrbManager', xpOrbManager);
        Services.register('enemyManager', enemyManager);
        // Note: CompanionManager will be registered in BaseGameScene

        // Systems
        Services.register('combatSystem', combatSystem);
        Services.register('spawnSystem', spawnSystem);
        Services.register('playerStatsSystem', playerStatsSystem);
        Services.register('levelProgressionSystem', levelProgressionSystem);
        Services.register('levelStatsTracker', levelStatsTracker);
        Services.register('magnetismSystem', magnetismSystem);

        // Mark services as initialized
        Services.initialize();
    }
}
